[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "study_smart"
version = "0.0.1"
authors = [
  { name="Magdalena Grubesa", email="magdalena.grubesa@student.uva.nl" },
]
description = "A smart study planner that builds your revision schedule automatically based on your exam dates and availability."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "pandas",
    "plotly",
    "dash>=2.4.0",
    "dash-bootstrap-components",
    "openpyxl",
    "google-auth",
    "google-auth-oauthlib",
    "google-api-python-client",
]
[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]
[project.urls]
Homepage = "https://github.com/Programming-The-Next-Step-2026/StudySmart"
Issues = "https://github.com/Programming-The-Next-Step-2026/StudySmart/issues"

